### ISSUE TITLE
Errors on Install Example

### ISSUE THREAD

**Issue by sphildreth** [coleifer/unqlite-python#14]
I installed using "pip install Cython unqlite"

Then I run this:

    python -c "import unqlite; unqlite.UnQLite()"

I get this:

    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "unqlite.pyx", line 285, in unqlite.UnQLite.__init__ (unqlite.c:1888)
    File "unqlite.pyx", line 296, in unqlite.UnQLite.open (unqlite.c:2003)
    TypeError: expected bytes, str found

My virtualenv is using Python version 3.4.3

**Comment by coleifer** [comment]
Windows?

**Comment by coleifer** [comment]
I don't really have plans for supporting Python 3 at this time.
