### ISSUE TITLE
Installation error: AttributeError: class Extension has no attribute '__mro__'

### ISSUE THREAD

**Issue by enderax** [coleifer/unqlite-python#37]
Hi,

Gave me following error while installing on . I've tried with pip and manual installation from source but no luck. 

From source:
```
python setup.py build
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    ext_modules=cythonize(unqlite_extension)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 818, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 648, in create_extension_list
    elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
  File "/usr/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/lib/python2.7/dist-packages/backports_abc.py", line 66, in __subclasshook__
    mro = C.__mro__
AttributeError: class Extension has no attribute '__mro__'

```

With pip:
```
#pip install cython unqlite
Requirement already satisfied: cython in /usr/local/lib/python2.7/dist-packages
Collecting unqlite
  Using cached unqlite-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-H9POLw/unqlite/setup.py", line 48, in <module>
        ext_modules=cythonize(unqlite_extension)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 818, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 648, in create_extension_list
        elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      File "/usr/lib/python2.7/abc.py", line 144, in __instancecheck__
        return cls.__subclasscheck__(subtype)
      File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/lib/python2.7/abc.py", line 161, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/usr/lib/python2.7/dist-packages/backports_abc.py", line 66, in __subclasshook__
        mro = C.__mro__
    AttributeError: class Extension has no attribute '__mro__'
```

**Comment by coleifer** [comment]
You're running into an issue between Cython and setuptools: https://github.com/cython/cython/issues/1507
