### ISSUE TITLE
Corrupt database when reading DB File from multiple processes

### ISSUE THREAD

**Issue by JonathanHuot** [coleifer/unqlite-python#5]
I tried to open two python consoles where one is writing, the other is reading. When the second read, exception is raised if changes have been committed but db file has not been reloaded cleanly:

Console 1:
```
>>> from unqlite import core
>>> db=core.UnQLite("test.db")
>>> db["xre"] = "test"
>>> "xre" in db
True
```

Console 2:
```
>>> from unqlite import core
>>> db=core.UnQLite("test.db")
>>> "xre" in db
False
```

Console 1:
```
>>> db.commit()
True
>>> "xre" in db
True
```

Console 2:
```
>>> print db["xre"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../unqlite/core.py", line 222, in fetch
    handle_return_value(rc)
  File ".../unqlite/core.py", line 24, in handle_return_value
    }.get(rc, 'Unknown exception: %s' % rc))
Exception: Corrupt database
>>> db=core.UnQLite("test.db")
>>> "xre" in db
True
```

**Comment by JonathanHuot** [comment]
Any comment on this before closing it ?

**Comment by coleifer** [comment]
Seems like an issue with UnQLite rather than the python wrapper.
