### ISSUE TITLE
subprocess.CalledProcessError: Command *** returned non-zero exit status 1

### ISSUE THREAD

**Issue by hnykda** [coleifer/unqlite-python#6]
Hello,

when I try to install unqlite using pip, i get this error:

```
Downloading/unpacking unqlite
  Downloading unqlite-0.1.9.tar.gz (528kB): 528kB downloaded
  Running setup.py (path:/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py) egg_info for package unqlite

    warning: no previously-included files found matching 'unqlite/_unqlite.py'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.so.0.1' found anywhere in distribution
Installing collected packages: unqlite
  Running setup.py install for unqlite
    Traceback (most recent call last):
      File "ctypesgen/ctypesgen.py", line 38, in <module>
        import ctypesgencore
      File "/home/dan/prac/.virtualenvs/work/build/unqlite/ctypesgen/ctypesgencore/__init__.py", line 56, in <module>
        import processor
    ImportError: No module named 'processor'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py", line 61, in <module>
        cmdclass={'build_py': GenerateCtypesWrapper},
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dan/prac/.virtualenvs/work/lib/python3.4/site-packages/setuptools/command/install.py", line 54, in run
        return _install.run(self)
      File "/usr/lib64/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py", line 28, in run
        wrapper])
      File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['python', 'ctypesgen/ctypesgen.py', 'unqlite/src/unqlite.h', '-L', './', '-l', 'unqlite', '-o', '/home/dan/prac/.virtualenvs/work/build/unqlite/unqlite/_unqlite.py']' returned non-zero exit status 1
    Complete output from command /home/dan/prac/.virtualenvs/work/bin/python3 -c "import setuptools, tokenize;__file__='/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-uz190krz-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dan/prac/.virtualenvs/work/include/site/python3.4:
    running install

running build

running build_py

Traceback (most recent call last):

  File "ctypesgen/ctypesgen.py", line 38, in <module>

    import ctypesgencore

  File "/home/dan/prac/.virtualenvs/work/build/unqlite/ctypesgen/ctypesgencore/__init__.py", line 56, in <module>

    import processor

ImportError: No module named 'processor'

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py", line 61, in <module>

    cmdclass={'build_py': GenerateCtypesWrapper},

  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/dan/prac/.virtualenvs/work/lib/python3.4/site-packages/setuptools/command/install.py", line 54, in run

    return _install.run(self)

  File "/usr/lib64/python3.4/distutils/command/install.py", line 539, in run

    self.run_command('build')

  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run

    self.run_command(cmd_name)

  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/dan/prac/.virtualenvs/work/build/unqlite/setup.py", line 28, in run

    wrapper])

  File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['python', 'ctypesgen/ctypesgen.py', 'unqlite/src/unqlite.h', '-L', './', '-l', 'unqlite', '-o', '/home/dan/prac/.virtualenvs/work/build/unqlite/unqlite/_unqlite.py']' returned non-zero exit status 1
```

Python 3.4 and Arch Linux x64.

**Comment by ul** [comment]
I have the same error with python2:

```
λ sudo pip2 install unqlite
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting unqlite
  Using cached unqlite-0.2.0.tar.gz
Installing collected packages: unqlite
  Running setup.py install for unqlite
    Complete output from command /usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-9CQUid/unqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OqrrYB-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "ctypesgen/ctypesgen.py", line 38, in <module>
        import ctypesgencore
      File "/tmp/pip-build-9CQUid/unqlite/ctypesgen/ctypesgencore/__init__.py", line 56, in <module>
        import processor
    ImportError: No module named 'processor'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9CQUid/unqlite/setup.py", line 61, in <module>
        cmdclass={'build_py': GenerateCtypesWrapper},
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-9CQUid/unqlite/setup.py", line 28, in run
        wrapper])
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['python', 'ctypesgen/ctypesgen.py', 'unqlite/src/unqlite.h', '-L', './', '-l', 'unqlite', '-o', '/tmp/pip-build-9CQUid/unqlite/unqlite/_unqlite.py']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-9CQUid/unqlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OqrrYB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9CQUid/unqlite
```

**Comment by vivekk1010** [comment]
hi, anyone got resolution.
