### ISSUE TITLE
Is it possible to use a samba shared database file?

### ISSUE THREAD

**Issue by mfmain** [coleifer/unqlite-python#63]
Here is my code:

```
from unqlite import *

db = UnQLite("/mnt/smb/1.unq")
db['foo'] = 'bar'
db.close()
```

This will only produce a zero byte file without any error reporting if file is located in a samba shared folder.
Adding db.commit() before db.close()  will get following trackback:

```
Traceback (most recent call last):
  File "/home/koi/tmp/1.py", line 6, in <module>
    db.commit()
  File "unqlite.pyx", line 527, in unqlite.UnQLite.commit
  File "unqlite.pyx", line 531, in unqlite.UnQLite.commit
  File "unqlite.pyx", line 490, in unqlite.UnQLite.check_call
unqlite.UnQLiteError: Another process or thread hold the requested lock
Another process or thread hold the requested lock
Another process or thread hold the requested lock
Cannot obtain an Exclusive lock on the target database
```
so, any solution? thanks!

**Comment by coleifer** [comment]
I doubt samba or nfs or other networked filesystems provide the locking operations needed. I'd consult the unqlite docs for questions on that.
